image: openjdk:17-oracle

stages:
  - stylecheck
  - build
  - test


cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stylecheck:
  stage: stylecheck
  script:
    - ./gradlew check

build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew test


after_script:
  - echo "End CI"