package de.unisaarland.cs.se.selab.game.entities;

public enum ParserMessage {
    DEFAULT, SUCCESSD, INVALIDMAXYEARORPLAYER, INVALIDDUNGEON, INVALIDINITALVALUE,
    INVALIDMONSTER, INVALIDADVENTURER, INVALIDTRAP, INVALIDROOM,
    NOTENOUGHMONSTERS, NOTENOUGHADVENTURERS, NOTENOUGHTRAPS, NOTENOUGHROOMS,
    IDDUPLICATIONMONSTER, IDDUPLICATIONADVENTURER, IDDUPLICATIONTRAPS, IDDUPLICATIONROOMS
}
